name: PR Cleanup

on:
  workflow_dispatch:
  pull_request:
    types:
    - closed

jobs:
  docker:
    name: docker cleanup
    runs-on: ubuntu-latest

    steps:
    - name: Get PR ID
      id: pr
      run: echo "::set-output name=id::$(echo ${{ github.ref_name }} | cut -d"/" -f1)"

    - name: Get package id
      id: container
      run: |
        export pr_id=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/user/packages/container/vault-assessment-prometheus-exporter/versions | jq -c '.[] | select(.metadata.container.tags | index("pr-${{ steps.pr.outputs.id }}")).id')
        echo "${{ github.api_url }}/user/packages/container/vault-assessment-prometheus-exporter/versions/$pr_id"
        curl  -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/user/packages/container/vault-assessment-prometheus-exporter/versions/$pr_id
