name: 'Clean up Docker images from PR'

on:
  pull_request:
    types: [closed]

env:
  BUILD_PR: ${{ secrets.BULD_PR }}

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
    - name: Build PR Check
      id: containers
      run: |
       if [[ "${{ secrets.BUILD_PR }}" != "" && \
             "${{ secrets.PR_CONTAINERS_USER }}" != "" && \
             "${{ secrets.PR_CONTAINERS }}" != "" ]]
       then
         echo "PR Builds configured"
         echo "::set-output name=BUILD_PR::true"
       else
         echo "PR Builds not configured"
         echo "::set-output name=BUILD_PR::false"
       fi
       
    - uses: eugene-davis/action-cleanup-package@v1.1.0
      with:
        package-name: ${{ github.event.repository.name }}
        tag: pr-${{ github.event.pull_request.number }}
        github-token: ${{ secrets.PR_CONTAINERS }}
        github-org: ${{ secrets.ORG}} # Should only be set when running in an organization
      if: ${{ fromJSON(steps.containers.outputs.BUILD_PR) }}
